name: Build and Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version from csproj
        id: get_version
        shell: pwsh
        run: |
          # Укажите правильный путь к вашему .csproj файлу
          $csprojPath = "BinanceBotWpf/BinanceBotWpf.csproj"
          if (-not (Test-Path $csprojPath)) {
            Write-Error "Файл не найден: $csprojPath"
            exit 1
          }
          [xml]$xml = Get-Content $csprojPath
          $version = $xml.Project.PropertyGroup.VersionPrefix
          if (-not $version) { $version = "1.0.0" }
          echo "VERSION=$version" >> $env:GITHUB_OUTPUT

      - name: Restore dependencies
        run: dotnet restore ${{ steps.get_version.outputs.csprojPath }}  # закомментировать

      - name: Publish
        run: dotnet publish BinanceBotWpf/BinanceBotWpf.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false -o ./publish

      - name: Create ZIP
        run: Compress-Archive -Path .\publish\* -DestinationPath BinanceBot_v${{ steps.get_version.outputs.VERSION }}.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          files: BinanceBot_v${{ steps.get_version.outputs.VERSION }}.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
